-- ====================================================================
-- SUPABASE DATABASE SCHEMA FOR QRYTUBE
-- This file provides the DDL to create the tables, indexes,
-- and Row Level Security (RLS) policies in your Supabase database.
-- Paste these commands directly into the Supabase SQL Editor.
-- ====================================================================

-- 1. Create the parent 'dynamic_qr' table to store redirection URLs
CREATE TABLE IF NOT EXISTS public.dynamic_qr (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    original_url TEXT NOT NULL,
    clicks INTEGER DEFAULT 0 NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Create the child 'qr_visits' table for detailed visitor analytics
CREATE TABLE IF NOT EXISTS public.qr_visits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    qr_id BIGINT REFERENCES public.dynamic_qr(id) ON DELETE CASCADE NOT NULL,
    country TEXT DEFAULT 'Unknown'::TEXT NOT NULL,
    device_type TEXT DEFAULT 'Desktop'::TEXT NOT NULL,
    browser TEXT DEFAULT 'Other'::TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. Optimization Indexes for lightning-fast queries and analytics aggregation
CREATE INDEX IF NOT EXISTS dynamic_qr_slug_idx ON public.dynamic_qr(slug);
CREATE INDEX IF NOT EXISTS qr_visits_qr_id_idx ON public.qr_visits(qr_id);
CREATE INDEX IF NOT EXISTS qr_visits_country_idx ON public.qr_visits(country);
CREATE INDEX IF NOT EXISTS qr_visits_created_at_idx ON public.qr_visits(created_at);

-- 4. Enable Row-Level Security (RLS) on both tables (Supabase Security Best Practice)
ALTER TABLE public.dynamic_qr ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.qr_visits ENABLE ROW LEVEL SECURITY;

-- 5. Row-Level Security (RLS) Access Policies for anonymous app visitors

-- Allow anyone to resolve a short URL by reading dynamic_qr records
CREATE POLICY "Allow public read-only access to dynamic_qr"
ON public.dynamic_qr FOR SELECT
TO anon, authenticated
USING (true);

-- Allow anyone to create a new dynamic QR code link from the application front-end
CREATE POLICY "Allow public insert to dynamic_qr"
ON public.dynamic_qr FOR INSERT
TO anon, authenticated
WITH CHECK (true);

-- Allow anyone to increment the click counter in dynamic_qr asynchronously during redirections
CREATE POLICY "Allow public updates to dynamic_qr clicks"
ON public.dynamic_qr FOR UPDATE
TO anon, authenticated
USING (true)
WITH CHECK (true);

-- Allow anyone to insert anonymous visitor analytics reports under qr_visits
CREATE POLICY "Allow public inserts to qr_visits"
ON public.qr_visits FOR INSERT
TO anon, authenticated
WITH CHECK (true);

-- Allow reading of analytics reports
CREATE POLICY "Allow public select access to qr_visits"
ON public.qr_visits FOR SELECT
TO anon, authenticated
USING (true);
